/* Tokens Tailwind exportados do Google Stitch — PH3A Studio v2 */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#484742",
        "surface-container-lowest": "#0e0e0e",
        tertiary: "#c7c6c6",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#af3000",
        error: "#ffb4ab",
        "on-primary": "#5f1600",
        "tertiary-fixed-dim": "#c7c6c6",
        "inverse-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "on-surface": "#e5e2e1",
        "tertiary-container": "#909191",
        "secondary-fixed-dim": "#c9c6c0",
        "on-background": "#e5e2e1",
        "tertiary-fixed": "#e3e2e2",
        "on-tertiary-fixed": "#1a1c1c",
        "on-error": "#690005",
        "error-container": "#93000a",
        primary: "#ffb59f",
        "surface-tint": "#ffb59f",
        "on-secondary-container": "#b8b5ae",
        surface: "#131313",
        "on-primary-container": "#531200",
        "outline-variant": "#5b4139",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        secondary: "#c9c6c0",
        "surface-container-highest": "#353535",
        "on-surface-variant": "#e3beb4",
        "secondary-fixed": "#e6e2db",
        "primary-container": "#fb5b28",
        "on-primary-fixed": "#3a0a00",
        "primary-fixed": "#ffdbd1",
        "on-secondary-fixed-variant": "#484742",
        "on-tertiary-container": "#292a2a",
        "surface-variant": "#353535",
        "on-primary-fixed-variant": "#862200",
        background: "#131313",
        "primary-fixed-dim": "#ffb59f",
        outline: "#aa8980",
        "surface-container": "#20201f",
        "surface-bright": "#393939",
        "on-tertiary": "#2f3131",
        "on-secondary-fixed": "#1c1c18",
        "on-tertiary-fixed-variant": "#464747",
        "on-secondary": "#31302c",
        "inverse-on-surface": "#313030",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin_mobile: "16px",
        margin_desktop: "40px",
        container_max_width: "1440px",
        base: "8px",
        nav_height: "56px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        code: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
      },
    },
  },
};
